import { SchemaValidationResult } from './definitions';
import { SchemaValidationError } from './definitions';
import { SchemaValidationWarning } from './definitions';
import { VALID_CONTRACT_CATEGORIES } from './ContractCategories';

/**
 * Contract Definition Validator
 * Validates contract definitions against the standard schema
 */
export class ContractDefinitionValidator {
  /**
   * Validates a contract definition against the schema
   */
  static validate(definition: any): SchemaValidationResult {
    const errors: SchemaValidationError[] = [];
    const warnings: SchemaValidationWarning[] = [];

    // Basic structure validation
    this.validateBasicStructure(definition, errors);
    if (errors.length > 0) {
      return { isValid: false, errors, warnings };
    }

    // Detailed validation
    this.validateId(definition.id, errors);
    this.validateName(definition.name, errors);
    this.validateCategory(definition.category, errors);
    this.validateStatus(definition.status, errors);
    this.validateVersion(definition.version, warnings);
    this.validateVariants(definition.variants, errors);
    this.validateProps(definition.props, errors);
    this.validateAccessibility(definition.accessibility, warnings);
    this.validateValidation(definition.validation, errors);
    this.validateSLA(definition.sla, warnings);

    return {
      isValid: errors.length === 0,
      errors,
      warnings
    };
  }

  private static validateBasicStructure(definition: any, errors: SchemaValidationError[]): void {
    if (!definition || typeof definition !== 'object') {
      errors.push({
        path: '',
        message: 'Contract definition must be an object',
        code: 'INVALID_TYPE'
      });
      return;
    }

    const required = ['name', 'category', 'variants', 'props'];
    for (const field of required) {
      if (!(field in definition)) {
        errors.push({
          path: field,
          message: `Required field '${field}' is missing`,
          code: 'MISSING_REQUIRED_FIELD'
        });
      }
    }
  }

  private static validateId(id: any, errors: SchemaValidationError[]): void {
    if (id === undefined || id === null) return; // ID is optional during creation (generated by entity)

    if (typeof id !== 'string') {
      errors.push({
        path: 'id',
        message: 'ID must be a string',
        code: 'INVALID_ID_TYPE',
        value: id
      });
      return;
    }

    // Spec: [namespace].[category].[name]
    // Allow alphanumeric, dots, hyphens, underscores.
    if (!/^[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)*$/.test(id)) {
      errors.push({
        path: 'id',
        message: 'ID must follow the format: namespace.category.name (e.g., ui.component.button)',
        code: 'INVALID_ID_FORMAT',
        value: id
      });
    }
  }

  private static validateStatus(status: any, errors: SchemaValidationError[]): void {
    if (status === undefined) return; // Optional, defaults to DRAFT

    const validStatuses = ['draft', 'validated', 'approved', 'active', 'deprecated', 'archived'];
    if (typeof status !== 'string') {
      errors.push({
        path: 'status',
        message: 'Status must be a string',
        code: 'INVALID_STATUS_TYPE',
        value: status
      });
      return;
    }

    if (!validStatuses.includes(status.toLowerCase())) {
      errors.push({
        path: 'status',
        message: `Status must be one of: ${validStatuses.join(', ')}`,
        code: 'INVALID_STATUS_VALUE',
        value: status
      });
    }
  }

  private static validateSLA(sla: any, warnings: SchemaValidationWarning[]): void {
    if (!sla) return;

    if (typeof sla !== 'object') {
      warnings.push({
        path: 'sla',
        message: 'SLA must be an object',
        code: 'INVALID_SLA_TYPE',
        value: sla
      });
      return;
    }

    // Check for common SLA metrics
    const metrics = ['latency', 'throughput', 'availability'];
    metrics.forEach(metric => {
      if (sla[metric] && typeof sla[metric] !== 'string') {
        warnings.push({
          path: `sla.${metric}`,
          message: `${metric} should be a string (e.g., "100ms", "99.9%")`,
          code: 'INVALID_SLA_METRIC_TYPE',
          value: sla[metric]
        });
      }
    });
  }

  private static validateName(name: any, errors: SchemaValidationError[]): void {
    if (typeof name !== 'string') {
      errors.push({
        path: 'name',
        message: 'Name must be a string',
        code: 'INVALID_NAME_TYPE',
        value: name
      });
      return;
    }

    if (name.length === 0) {
      errors.push({
        path: 'name',
        message: 'Name cannot be empty',
        code: 'EMPTY_NAME',
        value: name
      });
    }

    if (name.length > 100) {
      errors.push({
        path: 'name',
        message: 'Name cannot exceed 100 characters',
        code: 'NAME_TOO_LONG',
        value: name
      });
    }

    if (!/^[a-z][a-zA-Z0-9_-]*$/.test(name)) {
      errors.push({
        path: 'name',
        message: 'Name must follow kebab-case convention (lowercase, numbers, hyphens)',
        code: 'INVALID_NAME_FORMAT',
        value: name
      });
    }
  }

  private static validateCategory(category: any, errors: SchemaValidationError[]): void {
    const validCategories = VALID_CONTRACT_CATEGORIES;

    if (typeof category !== 'string') {
      errors.push({
        path: 'category',
        message: 'Category must be a string',
        code: 'INVALID_CATEGORY_TYPE',
        value: category
      });
      return;
    }

    if (!validCategories.includes(category as any)) {
      errors.push({
        path: 'category',
        message: `Category must be one of: ${validCategories.join(', ')}`,
        code: 'INVALID_CATEGORY_VALUE',
        value: category
      });
    }
  }

  private static validateVersion(version: any, warnings: SchemaValidationWarning[]): void {
    if (version === undefined) return;

    if (typeof version !== 'string') {
      warnings.push({
        path: 'version',
        message: 'Version should be a string',
        code: 'INVALID_VERSION_TYPE',
        value: version
      });
      return;
    }

    if (!/^\d+\.\d+\.\d+$/.test(version)) {
      warnings.push({
        path: 'version',
        message: 'Version should follow semantic versioning (x.y.z)',
        code: 'INVALID_VERSION_FORMAT',
        value: version
      });
    }
  }

  private static validateVariants(variants: any, errors: SchemaValidationError[]): void {
    if (!Array.isArray(variants)) {
      errors.push({
        path: 'variants',
        message: 'Variants must be an array',
        code: 'INVALID_VARIANTS_TYPE',
        value: variants
      });
      return;
    }

    if (variants.length === 0) {
      errors.push({
        path: 'variants',
        message: 'At least one variant is required',
        code: 'EMPTY_VARIANTS'
      });
      return;
    }

    const names = new Set<string>();
    variants.forEach((variant, index) => {
      const path = `variants[${index}]`;

      if (!variant || typeof variant !== 'object') {
        errors.push({
          path,
          message: 'Variant must be an object',
          code: 'INVALID_VARIANT_TYPE',
          value: variant
        });
        return;
      }

      // Check for duplicate names
      if (variant.name) {
        if (names.has(variant.name)) {
          errors.push({
            path: `${path}.name`,
            message: `Duplicate variant name: ${variant.name}`,
            code: 'DUPLICATE_VARIANT_NAME',
            value: variant.name
          });
        }
        names.add(variant.name);
      }

      // Validate required fields
      if (!variant.name) {
        errors.push({
          path: `${path}.name`,
          message: 'Variant name is required',
          code: 'MISSING_VARIANT_NAME'
        });
      }

      if (!variant.type) {
        errors.push({
          path: `${path}.type`,
          message: 'Variant type is required',
          code: 'MISSING_VARIANT_TYPE'
        });
      } else {
        const validTypes = ['size', 'intent', 'tone', 'emphasis', 'custom'];
        if (!validTypes.includes(variant.type)) {
          errors.push({
            path: `${path}.type`,
            message: `Variant type must be one of: ${validTypes.join(', ')}`,
            code: 'INVALID_VARIANT_TYPE',
            value: variant.type
          });
        }
      }

      if (!variant.values || !Array.isArray(variant.values) || variant.values.length === 0) {
        errors.push({
          path: `${path}.values`,
          message: 'Variant must have at least one value',
          code: 'EMPTY_VARIANT_VALUES',
          value: variant.values
        });
      }
    });
  }

  private static validateProps(props: any, errors: SchemaValidationError[]): void {
    if (!Array.isArray(props)) {
      errors.push({
        path: 'props',
        message: 'Props must be an array',
        code: 'INVALID_PROPS_TYPE',
        value: props
      });
      return;
    }

    if (props.length === 0) {
      errors.push({
        path: 'props',
        message: 'At least one prop is required',
        code: 'EMPTY_PROPS'
      });
      return;
    }

    const names = new Set<string>();
    props.forEach((prop, index) => {
      const path = `props[${index}]`;

      if (!prop || typeof prop !== 'object') {
        errors.push({
          path,
          message: 'Prop must be an object',
          code: 'INVALID_PROP_TYPE',
          value: prop
        });
        return;
      }

      // Check for duplicate names
      if (prop.name) {
        if (names.has(prop.name)) {
          errors.push({
            path: `${path}.name`,
            message: `Duplicate prop name: ${prop.name}`,
            code: 'DUPLICATE_PROP_NAME',
            value: prop.name
          });
        }
        names.add(prop.name);
      }

      // Validate required fields
      if (!prop.name) {
        errors.push({
          path: `${path}.name`,
          message: 'Prop name is required',
          code: 'MISSING_PROP_NAME'
        });
      }

      if (!prop.type) {
        errors.push({
          path: `${path}.type`,
          message: 'Prop type is required',
          code: 'MISSING_PROP_TYPE'
        });
      } else {
        const validTypes = ['string', 'number', 'boolean', 'array', 'object', 'function'];
        if (!validTypes.includes(prop.type)) {
          errors.push({
            path: `${path}.type`,
            message: `Prop type must be one of: ${validTypes.join(', ')}`,
            code: 'INVALID_PROP_TYPE',
            value: prop.type
          });
        }
      }

      if (typeof prop.required !== 'boolean') {
        errors.push({
          path: `${path}.required`,
          message: 'Prop required field must be a boolean',
          code: 'INVALID_PROP_REQUIRED',
          value: prop.required
        });
      }
    });
  }

  private static validateAccessibility(accessibility: any, warnings: SchemaValidationWarning[]): void {
    if (!accessibility) return;

    if (accessibility.supported && !accessibility.roles?.length) {
      warnings.push({
        path: 'accessibility.roles',
        message: 'Accessibility-enabled contracts should define supported roles',
        code: 'MISSING_ACCESSIBILITY_ROLES'
      });
    }

    if (accessibility.supported && !accessibility.keyboardActions?.length) {
      warnings.push({
        path: 'accessibility.keyboardActions',
        message: 'Accessibility-enabled contracts should define keyboard actions',
        code: 'MISSING_KEYBOARD_ACTIONS'
      });
    }
  }

  private static validateValidation(validation: any, errors: SchemaValidationError[]): void {
    if (!validation) return; // Optional

    if (!Array.isArray(validation)) {
      errors.push({
        path: 'validation',
        message: 'Validation must be an array of rules',
        code: 'INVALID_VALIDATION_TYPE',
        value: validation
      });
      return;
    }

    validation.forEach((rule, index) => {
      const path = `validation[${index}]`;
      if (!rule || typeof rule !== 'object') {
        errors.push({
          path,
          message: 'Validation rule must be an object',
          code: 'INVALID_VALIDATION_RULE_TYPE',
          value: rule
        });
        return;
      }
      
      const validTypes = ['required', 'range', 'pattern', 'custom'];
      if (!rule.type || !validTypes.includes(rule.type)) {
        errors.push({
          path: `${path}.type`,
          message: `Validation rule type must be one of: ${validTypes.join(', ')}`,
          code: 'INVALID_VALIDATION_RULE_TYPE_VALUE',
          value: rule.type
        });
      }

      if (!rule.target || typeof rule.target !== 'string') {
        errors.push({
          path: `${path}.target`,
          message: 'Validation rule target must be a string',
          code: 'MISSING_VALIDATION_RULE_TARGET',
          value: rule.target
        });
      }

      // Specific check for custom validation
      if (rule.type === 'custom') {
         if (!rule.params?.script || typeof rule.params.script !== 'string') {
           errors.push({
             path: `${path}.params.script`,
             message: 'Custom validation rule must provide a script in params',
             code: 'MISSING_CUSTOM_VALIDATOR_SCRIPT'
           });
         }
      }
    });
  }
}
